---
- name: converge
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Get path to php.ini
      find:
        paths: /etc/php
        file_type: directory
        recurse: no
      register: ini_path

    - name: Update php.ini post_max_size
      replace:
        dest: "{{ ini_path.files[0].path }}/apache2/php.ini"
        regexp: '^post_max_size.*$'
        replace: 'post_max_size = 1024M'
        backup: yes

    - name: Update php.ini max_input_vars
      replace:
        dest: "{{ ini_path.files[0].path }}/apache2/php.ini"
        regexp: '^;max_input_vars.*$'
        replace: 'max_input_vars = 5000'
        backup: yes

    - name: Apache2 restart
      ansible.builtin.service:
        name: apache2
        state: restarted
        enabled: true

  roles:
    - role: ansible-role-moodle
